# Generated by Django 5.2.2 on 2026-04-15 17:15

import datetimeutc.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('updated_at', datetimeutc.fields.DateTimeUTCField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('p_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclature.category')),
            ],
            options={
                'unique_together': {('id', 'p_category')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('updated_at', datetimeutc.fields.DateTimeUTCField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
            options={
                'unique_together': {('name', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('updated_at', datetimeutc.fields.DateTimeUTCField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclature.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('updated_at', datetimeutc.fields.DateTimeUTCField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nomenclature.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclature.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclature.product')),
            ],
        ),
    ]
