# Generated by Django 5.2.2 on 2026-04-16 09:08

from django.db import migrations


def create_category(apps, schema_editor):
    Category = apps.get_model("nomenclature", "Category")
    main_category = Category()
    main_category.name = 'Бытовая техника'
    main_category.save()
    category = Category()
    category.name = 'Стиральные машины'
    category.p_category_id = main_category.id
    category.save()
    category = Category()
    category.name = 'Телевизоры'
    category.p_category_id = main_category.id
    category.save()
    category = Category()
    category.name = 'Холодильники'
    category.p_category_id = main_category.id
    category.save()
    ch_category = Category()
    ch_category.name = 'однокамерные'
    ch_category.p_category_id = category.id
    ch_category.save()
    ch_category = Category()
    ch_category.name = 'двухкамерные'
    ch_category.p_category_id = category.id
    ch_category.save()
    main_category = Category()
    main_category.name = 'Компьютеры'
    main_category.save()
    category = Category()
    category.name = 'Ноутбуки'
    category.p_category_id = main_category.id
    category.save()
    ch_category = Category()
    ch_category.name = '17"'
    ch_category.p_category_id = category.id
    ch_category.save()
    ch_category = Category()
    ch_category.name = '19"'
    ch_category.p_category_id = category.id
    ch_category.save()
    category = Category()
    category.name = 'Моноблоки'
    category.p_category_id = main_category.id
    category.save()


class Migration(migrations.Migration):
    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_category),
    ]
